# Generated by Django 4.2.18 on 2025-01-17 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Текст уведомления, которое будет отправлено",
                        max_length=1024,
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "delay",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Без задержки"), (1, "1 час"), (2, "1 день")],
                        default=0,
                        help_text="Задержка перед отправкой уведомления",
                        verbose_name="Задержка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания уведомления",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recepient",
                    models.CharField(
                        help_text="Email или ID Telegram",
                        max_length=150,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "recepient_type",
                    models.CharField(
                        choices=[("email", "Email"), ("telegram", "Telegram")],
                        help_text="Тип получателя (Email или Telegram)",
                        max_length=50,
                        verbose_name="Тип получателя",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notifications.notification",
                        verbose_name="Уведомление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель уведомления",
                "verbose_name_plural": "Получатели уведомлений",
            },
        ),
        migrations.CreateModel(
            name="NotificationSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email или номер телефона получателя",
                        max_length=150,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("email", "Email"), ("telegram", "Telegram")],
                        help_text="Тип получателя (Email или телефон)",
                        max_length=50,
                        verbose_name="Тип получателя",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Ok", "Ok"), ("Error", "Error")],
                        help_text="Статус отправки уведомления",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Текст ошибки, если отправка не удалась",
                        null=True,
                        verbose_name="Сообщение об ошибке",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата и время попытки отправки уведомления",
                        verbose_name="Время попытки отправки",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                        verbose_name="Уведомление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог отправки уведомления",
                "verbose_name_plural": "Логи отправки уведомлений",
                "ordering": ["-timestamp"],
            },
        ),
    ]
